//
// Created by SomeDude on 01.09.2019.
//

#ifndef CMQTTSNFORWARDER_MQTTSNCLIENTFINDGATEWAYPATTERN_H
#define CMQTTSNFORWARDER_MQTTSNCLIENTFINDGATEWAYPATTERN_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum MQTT_SN_CLIENT_FIND_GW_PATTERN_ {
    MQTT_SN_CLIENT_FIND_GW_PATTERN_ADVERTISE,
    MQTT_SN_CLIENT_FIND_GW_PATTERN_SEARCHGW,
    MQTT_SN_CLIENT_FIND_GW_PATTERN_DIRECT
} MQTT_SN_CLIENT_FIND_GW_PATTERN;

#ifdef __cplusplus
}
#endif

#endif  //CMQTTSNFORWARDER_MQTTSNCLIENTFINDGATEWAYPATTERN_H
