//
// Created by SomeDude on 25.08.2019.
//

#ifndef CMQTTSNFORWARDER_MQTTSNCLIENTMSGHANDLERRETURNVALUE_H
#define CMQTTSNFORWARDER_MQTTSNCLIENTMSGHANDLERRETURNVALUE_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum MQTT_SN_CLIENT_MSG_HANDLER_RETURN_CODE_ {
    MQTT_SN_CLIENT_LOOP_RETURN_ERROR   = -1,
    MQTT_SN_CLIENT_LOOP_RETURN_SUCCESS = 0,
    MQTT_SN_CLIENT_LOOP_RETURN_TIMEOUT,
    MQTT_SN_CLIENT_LOOP_RETURN_PARSEERROR,
    MQTT_SN_CLIENT_LOOP_RETURN_UNHANDLEDMSG,
    MQTT_SN_CLIENT_LOOP_RETURN_NOTAWAITEDMSG,
    MQTT_SN_CLIENT_LOOP_RETURN_QOS2RECEIVETIMOUT
} MQTT_SN_CLIENT_LOOP_RETURN_CODE;

#ifdef __cplusplus
}
#endif
#endif  //CMQTTSNFORWARDER_MQTTSNCLIENTMSGHANDLERRETURNVALUE_H
