//
// Created by SomeDude on 25.08.2019.
//

#ifndef CMQTTSNFORWARDER_MQTTSNCLIENTCONFIG_H
#define CMQTTSNFORWARDER_MQTTSNCLIENTCONFIG_H

#include "MqttSnClientFindGatewayPattern.h"

#ifdef __cplusplus
extern "C" {
#endif

#define WITH_PAHO_WAKEUP_WORKAROUND
#define WITH_PAHO_AWAKE_QOS_WORKAROUND

#ifndef WITHOUT_MQTT_SN_CLIENT_NETWORK_WHITELIST
#define WITH_MQTT_SN_CLIENT_NETWORK_WHITELIST
#endif

#ifndef WITHOUT_MQTT_SN_CLIENT_NETWORK_BLACKLIST
#define WITH_MQTT_SN_CLIENT_NETWORK_BLACKLIST
#endif

#ifndef WITHOUT_ADVERTISE_GATEWAY_DISCOVERED_LIST
#define WITH_ADVERTISE_GATEWAY_DISCOVERED_LIST
#endif

#ifndef WITHOUT_GWINFO_GATEWAY_DISCOVERED_LIST
#define WITH_GWINFO_GATEWAY_DISCOVERED_LIST
#endif

#ifndef WITHOUT_MQTT_SN_CLIENT_AUTO_CONNECT
#define WITH_MQTT_SN_CLIENT_AUTO_CONNECT
#endif

#define WITH_MQTT_SN_CLIENT_BUFFER

#ifndef MQTT_SN_CLIENT_DEFAULT_FIND_GW_PATTERN
#define MQTT_SN_CLIENT_DEFAULT_FIND_GW_PATTERN MQTT_SN_CLIENT_FIND_GW_PATTERN_SEARCHGW
#endif

#ifndef WITH_MQTT_SN_CLIENT_AUTO_RECONNECT
#define WITH_MQTT_SN_CLIENT_AUTO_RECONNECT
#endif

#ifndef WITH_MQTT_SN_CLIENT_AUTO_RECONNECT_DEFAULT_ENABLED
#define WITH_MQTT_SN_CLIENT_AUTO_RECONNECT_DEFAULT_ENABLED 1
#endif

#ifndef WITH_MQTT_SN_CLIENT_WHITELIST
#define WITH_MQTT_SN_CLIENT_WHITELIST
#endif
#ifdef WITH_MQTT_SN_CLIENT_WHITELIST
#define MQTT_SN_CLIENT_GW_ID_WHITELIST_LENGTH 5
#define MQTT_SN_CLIENT_GW_ADDRESS_WHITELIST_LENGTH 5
#endif

#ifndef WITH_MQTT_SN_CLIENT_BLACKLIST
#define WITH_MQTT_SN_CLIENT_BLACKLIST
#endif
#ifdef WITH_MQTT_SN_CLIENT_BLACKLIST
#define MQTT_SN_CLIENT_GW_ID_BLACKLIST_LENGTH 5
#define MQTT_SN_CLIENT_GW_ADDRESS_BLACKLIST_LENGTH 5
#endif

#ifndef MQTT_SN_CLIENT_SEARCHGW_REPLY_DEFAULT_ENABLED
#define MQTT_SN_CLIENT_SEARCHGW_REPLY_DEFAULT_ENABLED 1
#endif

#ifndef MQTT_SN_CLIENT_GWINFO_DELAY_MS
#define MQTT_SN_CLIENT_GWINFO_DELAY_MS 5000
#endif

#ifndef MQTT_SN_CLIENT_PROTOCOL_ID
#define MQTT_SN_CLIENT_PROTOCOL_ID 0x01
#endif

#ifndef MQTT_SN_CLIENT_DEFAULT_RETRY_TIMEOUT_MS
#define MQTT_SN_CLIENT_DEFAULT_RETRY_TIMEOUT_MS 5000
#endif

#ifndef MQTT_SN_CLIENT_DEFAULT_RETRY_COUNT
#define MQTT_SN_CLIENT_DEFAULT_RETRY_COUNT 1
#endif

#ifndef MQTT_SN_CLIENT_DEFAULT_SIGNAL_STRENGTH
#define MQTT_SN_CLIENT_DEFAULT_SIGNAL_STRENGTH 1
#endif

#ifndef MQTT_SN_CLIENT_DEFAULT_LOW_TIMEOUT_THRESHOLD
#define MQTT_SN_CLIENT_DEFAULT_LOW_TIMEOUT_THRESHOLD 60
#endif

#ifndef MQTT_SN_CLIENT_DEFAULT_LOW_TIMEOUT_THRESHOLD_PERCENTAGE
#define MQTT_SN_CLIENT_DEFAULT_LOW_TIMEOUT_THRESHOLD_PERCENTAGE 50
#endif

#ifndef MQTT_SN_CLIENT_DEFAULT_HIGHT_TIMEOUT_THRESHOLD_PERCENTAGE
#define MQTT_SN_CLIENT_DEFAULT_HIGHT_TIMEOUT_THRESHOLD_PERCENTAGE 10
#endif

#ifndef MQTT_SN_CLIENT_MAX_REGISTRATIONS
#define MQTT_SN_CLIENT_MAX_REGISTRATIONS 10
#endif

#ifndef MQTT_SN_CLIENT_MAX_MESSAGES_IN_FLIGHT
#define MQTT_SN_CLIENT_MAX_MESSAGES_IN_FLIGHT 5
#endif

#ifndef MQTT_SN_CLIENT_PING_REQ_ADVANCE_TIME_S
#define MQTT_SN_CLIENT_PING_REQ_ADVANCE_TIME_S 10
#endif

#ifndef MQTT_SN_CLIENT_MAX_REGISTRATION_TOPIC_NAME_LENGTH
#define MQTT_SN_CLIENT_MAX_REGISTRATION_TOPIC_NAME_LENGTH 255
#endif

#ifdef WITH_MQTT_SN_CLIENT_BUFFER
#ifndef MQTT_SN_CLIENT_MAX_WILL_TOPIC_LENGTH
#define MQTT_SN_CLIENT_MAX_WILL_TOPIC_LENGTH 255
#endif

#ifndef MQTT_SN_CLIENT_MAX_WILL_MSG_LENGTH
#define MQTT_SN_CLIENT_MAX_WILL_MSG_LENGTH 255
#endif

typedef struct MqttSnClientBuffer_ {
    char    client_id[MQTT_SN_MAX_CLIENT_ID_LENGTH];
    uint8_t client_id_length;

    char     will_topic[MQTT_SN_CLIENT_MAX_WILL_TOPIC_LENGTH];
    uint16_t will_topic_length;

    uint8_t *will_msg;
    uint16_t will_msg_len;

} MqttSnClientBuffer;
#endif

#ifdef __cplusplus
}
#endif
#endif  //CMQTTSNFORWARDER_MQTTSNCLIENTCONFIG_H
