//
// Created by SomeDude on 25.08.2019.
//

#ifndef CMQTTSNFORWARDER_MQTTSNCLIENTCONNECTIONSTATUS_H
#define CMQTTSNFORWARDER_MQTTSNCLIENTCONNECTIONSTATUS_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum MQTT_SN_CLIENT_CONNECTION_STATUS_ {
    MQTT_SN_CLIENT_CONNECTION_STATUS_ERROR        = -2,
    MQTT_SN_CLIENT_CONNECTION_STATUS_UNINITALIZED = -1,
    MQTT_SN_CLIENT_CONNECTION_STATUS_INITALIZED   = 0,
    MQTT_SN_CLIENT_CONNECTION_STATUS_GATEWAY_LOST = 1,
    MQTT_SN_CLIENT_CONNECTION_STATUS_DISCONNECTED = 2,
    MQTT_SN_CLIENT_CONNECTION_STATUS_CONNECTED,
    MQTT_SN_CLIENT_CONNECTION_STATUS_ASLEEP,
    MQTT_SN_CLIENT_CONNECTION_STATUS_AWAKE,
} MQTT_SN_CLIENT_STATUS;

#ifdef __cplusplus
}
#endif
#endif  //CMQTTSNFORWARDER_MQTTSNCLIENTCONNECTIONSTATUS_H
