//
// Created by SomeDude on 01.08.2019.
//

#ifndef CMQTTSNFORWARDER_INPUT_MQTTSNINPUTINTERFACE_H_
#define CMQTTSNFORWARDER_INPUT_MQTTSNINPUTINTERFACE_H_

#endif //CMQTTSNFORWARDER_INPUT_MQTTSNINPUTINTERFACE_H_
