//
// Created by SomeDude on 30.07.2019.
//

#ifndef CMQTTSNFORWARDER_TEST_MQTTBROKER_MQTTBROKERPROTOCOLTESTTYPE_H_
#define CMQTTSNFORWARDER_TEST_MQTTBROKER_MQTTBROKERPROTOCOLTESTTYPE_H_

enum class MqttBrokerProtocolTestType {
  TCP // TODO WEBSOCKET not implemented yet
};

#endif //CMQTTSNFORWARDER_TEST_MQTTBROKER_MQTTBROKERPROTOCOLTESTTYPE_H_
