//
// Created by SomeDude on 30.07.2019.
//

#ifndef CMQTTSNFORWARDER_TEST_MQTTBROKER_MQTTBROKERPROTOCOLTESTTYPE_H_
#define CMQTTSNFORWARDER_TEST_MQTTBROKER_MQTTBROKERPROTOCOLTESTTYPE_H_

// FEATURE WEBSOCKET
enum class MqttBrokerProtocolTestType {
  TCP, WEBSOCKET
};

#endif //CMQTTSNFORWARDER_TEST_MQTTBROKER_MQTTBROKERPROTOCOLTESTTYPE_H_
