kind: pipeline
name: default

steps:
  - name: prepare
    image: ubuntu
    commands:
      - apt-get update && apt-get install -y git cmake gcc g++
      - cmake -DCMAKE_BUILD_TYPE=Debug -G "CodeBlocks - Unix Makefiles"
      - make MqttSnClientNetworkInterfaceUnitTests
      - ./MqttSnClientNetworkInterfaceUnitTests --gtest_filter=* --gtest_color=yes --gtest_output="xml:/MqttSnClientNetworkInterfaceUnitTestsReport.xml"
      - make MqttSnGatewayNetworkInterfaceUnitTests
      - ./MqttSnGatewayNetworkInterfaceUnitTests --gtest_filter=* --gtest_color=yes --gtest_output="xml:/MqttSnGatewayNetworkInterfaceUnitTestsReport.xml"
      - make MqttSnFixedSizeRingBufferUnitTests
      - ./MqttSnFixedSizeRingBufferUnitTests --gtest_filter=* --gtest_color=yes --gtest_output="xml:/MqttSnFixedSizeRingBufferUnitTestsReport.xml"
      - make MqttSnForwarderLinuxTcpGatewayNetworkTests
      - ./MqttSnForwarderLinuxTcpGatewayNetworkTests --gtest_filter=* --gtest_color=yes --gtest_output="xml:/MqttSnForwarderIntegrationTestsReport.xml"
