---
kind: pipeline
name: prepare_reports

steps:
  - name: prepare_reports
    image: ubuntu
    volumes:
      - name: reports
        path: /var/local/drone/reports
    commands:
      - mkdir --parents /var/local/drone/reports/${DRONE_REPO}/${DRONE_BUILD_NUMBER}
      - echo "DRONE_BRANCH ${DRONE_BRANCH}\n
        DRONE_BUILD_CREATED ${DRONE_BUILD_CREATED}\n
        DRONE_BUILD_EVENT ${DRONE_BUILD_EVENT}\n
        DRONE_BUILD_NUMBER ${DRONE_BUILD_NUMBER}\n
        DRONE_BUILD_STARTED ${DRONE_BUILD_STARTED}\n
        DRONE_COMMIT_AFTER ${DRONE_COMMIT_AFTER}\n
        DRONE_COMMIT_AUTHOR ${DRONE_COMMIT_AUTHOR}\n
        DRONE_COMMIT_AUTHOR_AVATAR ${DRONE_COMMIT_AUTHOR_AVATAR}\n
        DRONE_COMMIT_AUTHOR_EMAIL ${DRONE_COMMIT_AUTHOR_EMAIL}\n
        DRONE_COMMIT_AUTHOR_NAME ${DRONE_COMMIT_AUTHOR_NAME}\n
        DRONE_COMMIT_BEFORE ${DRONE_COMMIT_BEFORE}\n
        DRONE_COMMIT_BRANCH ${DRONE_COMMIT_BRANCH}\n
        DRONE_COMMIT_LINK ${DRONE_COMMIT_LINK}\n
        DRONE_COMMIT ${DRONE_COMMIT}\n
        DRONE_COMMIT_MESSAGE ${DRONE_COMMIT_MESSAGE}\n
        DRONE_COMMIT_REF ${DRONE_COMMIT_REF}\n
        DRONE_COMMIT_SHA ${DRONE_COMMIT_SHA}\n
        DRONE_GIT_HTTP_URL ${DRONE_GIT_HTTP_URL}\n
        DRONE_GIT_SSH_URL ${DRONE_GIT_SSH_URL}\n
        DRONE_MACHINE ${DRONE_MACHINE}\n
        DRONE_PULL_REQUEST ${DRONE_PULL_REQUEST}\n
        DRONE_REPO ${DRONE_REPO}\n
        DRONE_REPO_BRANCH ${DRONE_REPO_BRANCH}\n
        DRONE_REMOTE_URL ${DRONE_REMOTE_URL}\n
        DRONE_REPO_LINK ${DRONE_REPO_LINK}\n
        DRONE_REPO_NAME ${DRONE_REPO_NAME}\n
        DRONE_REPO_NAMESPACE ${DRONE_REPO_NAMESPACE}\n
        DRONE_REPO_PRIVATE ${DRONE_REPO_PRIVATE}\n
        DRONE_REPO_SCM ${DRONE_REPO_SCM}\n
        DRONE_REPO_VISIBILITY ${DRONE_REPO_VISIBILITY}\n
        DRONE_RUNNER_HOST ${DRONE_RUNNER_HOST}\n
        DRONE_RUNNER_HOSTNAME ${DRONE_RUNNER_HOSTNAME}\n
        DRONE_RUNNER_PLATFORM ${DRONE_RUNNER_PLATFORM}\n
        DRONE_SOURCE_BRANCH ${DRONE_SOURCE_BRANCH}\n
        DRONE_SYSTEM_HOST ${DRONE_SYSTEM_HOST}\n
        DRONE_SYSTEM_HOSTNAME ${DRONE_SYSTEM_HOSTNAME}\n
        DRONE_RUNNER_LABEL ${DRONE_RUNNER_LABEL}\n
        DRONE_SYSTEM_VERSION ${DRONE_SYSTEM_VERSION}\n
        DRONE_TAG ${DRONE_TAG}\n
        DRONE_TARGET_BRANCH ${DRONE_TARGET_BRANCH}\n" > /var/local/drone/reports/${DRONE_REPO}/${DRONE_BUILD_NUMBER}/config


volumes:
  - name: reports
    host:
      path: /var/local/drone/reports
---
kind: pipeline
name: build

clone:
  disabled: true

steps:
  - name: build
    image: ubuntu
    volumes:
      - name: reports
        path: /var/local/drone/reports
    commands:
      - ls -l
      - apt-get update && apt-get install -y git cmake gcc g++ 2>&1 | tee /var/local/drone/reports/${DRONE_REPO}/${DRONE_BUILD_NUMBER}/aptget_report
      - cmake -DCMAKE_BUILD_TYPE=Debug -G "CodeBlocks - Unix Makefiles" 2>&1 | tee /var/local/drone/reports/${DRONE_REPO}/${DRONE_BUILD_NUMBER}/cmake_report
      - make MqttSnClientNetworkInterfaceUnitTests
      - make MqttSnGatewayNetworkInterfaceUnitTests
      - make MqttSnFixedSizeRingBufferUnitTests
      - make MqttSnForwarderIntegrationTests
      - make MqttSnForwarderLinuxTcpClientNetworkTests
      - make MqttSnForwarderLinuxTcpGatewayNetworkTests
      - cp MqttSnForwarderLinuxTcpClientNetworkTests MqttSnClientNetworkInterfaceMessageDefragmentationTests
      - cp MqttSnForwarderLinuxTcpClientNetworkTests SendMultipleClientMultipleMessageVariableLength
      - cp MqttSnForwarderLinuxTcpClientNetworkTests ReceiveMultipleClientMultipleMessageVariableLength
      - cp MqttSnForwarderLinuxTcpClientNetworkTests SendToClientsReceiveOnForwarderTests
      - cp MqttSnForwarderLinuxTcpClientNetworkTests ReceiveOnForwarderSendToClientTests
      - cp MqttSnForwarderLinuxTcpGatewayNetworkTests GatewayDefragmentationTests
      - cp MqttSnForwarderLinuxTcpGatewayNetworkTests SendToGateway
      - cp MqttSnForwarderLinuxTcpGatewayNetworkTests ReceiveFromGateway
      - cp MqttSnForwarderLinuxTcpGatewayNetworkTests SendToGatewayReceiveOnForwarder
      - cp MqttSnForwarderLinuxTcpGatewayNetworkTests ReceiveFromGatewaySendToGateway

volumes:
  - name: reports
    host:
      path: /var/local/drone/reports

trigger:
  status: [ success ]

depends_on:
- prepare_reports

---
kind: pipeline
name: unit_test

clone:
  disabled: true

steps:
  - name: MqttSnClientNetworkInterfaceUnitTests
    image: ubuntu
    commands:
      - ls -l
      - ./MqttSnClientNetworkInterfaceUnitTests
        --gtest_output=xml:MqttSnClientNetworkInterfaceUnitTests.xml
        --gtest_filter=* --gtest_color=yes

  - name: MqttSnGatewayNetworkInterfaceUnitTests
    image: ubuntu
    commands:
      - ./MqttSnGatewayNetworkInterfaceUnitTests
        --gtest_output=xml:MqttSnGatewayNetworkInterfaceUnitTests.xml
        --gtest_filter=* --gtest_color=yes

  - name: MqttSnFixedSizeRingBufferUnitTests
    image: ubuntu
    commands:
      - ./MqttSnFixedSizeRingBufferUnitTests
        --gtest_output=xml:MqttSnFixedSizeRingBufferUnitTests.xml
        --gtest_filter=* --gtest_color=yes

  - name: MqttSnForwarderIntegrationTests
    image: ubuntu
    commands:
      - ./MqttSnForwarderIntegrationTests
        --gtest_output=xml:MqttSnForwarderIntegrationTests.xml
        --gtest_filter=* --gtest_color=yes

trigger:
  status:
  - success

depends_on:
- build

---
kind: pipeline
name: gather_unittest_reports

steps:
  - name: gather_unittest_reports
    image: ubuntu
    volumes:
      - name: reports
        path: /var/local/drone/reports
    commands:
      - ls -l
      - cp MqttSnClientNetworkInterfaceUnitTests.xml /var/local/drone/reports/${DRONE_REPO}/${DRONE_BUILD_NUMBER}/MqttSnClientNetworkInterfaceUnitTests.xml
      - cp MqttSnGatewayNetworkInterfaceUnitTests.xml /var/local/drone/reports/${DRONE_REPO}/${DRONE_BUILD_NUMBER}/MqttSnGatewayNetworkInterfaceUnitTests.xml
      - cp MqttSnFixedSizeRingBufferUnitTests.xml /var/local/drone/reports/${DRONE_REPO}/${DRONE_BUILD_NUMBER}/MqttSnFixedSizeRingBufferUnitTests.xml
      - cp MqttSnForwarderIntegrationTests.xml /var/local/drone/reports/${DRONE_REPO}/${DRONE_BUILD_NUMBER}/MqttSnForwarderIntegrationTests.xml

trigger:
  status:
  - success
  - failure

depends_on:
- unit_test

