kind: pipeline
name: default

steps:
  - name: prepare
    image: ubuntu
    commands:
    - apt-get update && apt-get install -y cmake gcc
    - cmake -DCMAKE_BUILD_TYPE=Debug -G "CodeBlocks - Unix Makefiles"
    - make MqttSnForwarder_LinuxTcpClientNetwork_Tests
    - ./MqttSnForwarder_LinuxTcpClientNetwork_Tests

