kind: pipeline
name: default

steps:
  - name: prepare
    image: ubuntu
    volumes:
      - name: report
        path: ~/
    commands:
      - apt-get update && apt-get install -y git cmake gcc g++
      - cmake -DCMAKE_BUILD_TYPE=Debug -G "CodeBlocks - Unix Makefiles"
      - make MqttSnForwarderIntegrationTests
      - MqttSnForwarderIntegrationTests --gtest_filter=* --gtest_color=yes --gtest_output="xml:~/XML_Report.xml"
      - cat ~\XML_Report.xml
volumes:
  - name: report
    host:
      path: /tmp/cmqttsnforwarder
