kind: pipeline
name: default

steps:
  - name: build
    image: ubuntu
    depends_on: [ clone ]
    commands:
      - apt-get update && apt-get install -y git cmake gcc g++
      - cmake -DCMAKE_BUILD_TYPE=Debug -G "CodeBlocks - Unix Makefiles"
      - make MqttSnClientNetworkInterfaceUnitTests
      - make MqttSnGatewayNetworkInterfaceUnitTests
      - make MqttSnFixedSizeRingBufferUnitTests
      - make MqttSnForwarderIntegrationTests
      - make MqttSnForwarderLinuxTcpClientNetworkTests
      - make MqttSnForwarderLinuxTcpGatewayNetworkTests
      - cp MqttSnForwarderLinuxTcpClientNetworkTests MqttSnClientNetworkInterfaceMessageDefragmentationTests
      - cp MqttSnForwarderLinuxTcpClientNetworkTests SendMultipleClientMultipleMessageVariableLength
      - cp MqttSnForwarderLinuxTcpClientNetworkTests ReceiveMultipleClientMultipleMessageVariableLength
      - cp MqttSnForwarderLinuxTcpClientNetworkTests SendToClientsReceiveOnForwarderTests
      - cp MqttSnForwarderLinuxTcpClientNetworkTests ReceiveOnForwarderSendToClientTests
      - cp MqttSnForwarderLinuxTcpGatewayNetworkTests GatewayDefragmentationTests
      - cp MqttSnForwarderLinuxTcpGatewayNetworkTests SendToGateway
      - cp MqttSnForwarderLinuxTcpGatewayNetworkTests ReceiveFromGateway
      - cp MqttSnForwarderLinuxTcpGatewayNetworkTests SendToGatewayReceiveOnForwarder
      - cp MqttSnForwarderLinuxTcpGatewayNetworkTests ReceiveFromGatewaySendToGateway

  - name: MqttSnClientNetworkInterfaceUnitTests
    image: ubuntu
    depends_on: [ build ]
    commands:
      - ./MqttSnClientNetworkInterfaceUnitTests --gtest_filter=* --gtest_color=yes

  - name: MqttSnGatewayNetworkInterfaceUnitTests
    image: ubuntu
    depends_on: [ build ]
    commands:
      - ./MqttSnGatewayNetworkInterfaceUnitTests --gtest_filter=* --gtest_color=yes

  - name: MqttSnFixedSizeRingBufferUnitTests
    image: ubuntu
    depends_on: [ build ]
    commands:
      - ./MqttSnFixedSizeRingBufferUnitTests --gtest_filter=* --gtest_color=yes

  - name: MqttSnForwarderIntegrationTests
    image: ubuntu
    depends_on: [ build ]
    commands:
      - ./MqttSnForwarderIntegrationTests --gtest_color=yes


  - name: MqttSnClientNetworkInterfaceMessageDefragmentationTests
    image: ubuntu
    depends_on: [ MqttSnClientNetworkInterfaceUnitTests, MqttSnGatewayNetworkInterfaceUnitTests, MqttSnFixedSizeRingBufferUnitTests, MqttSnForwarderIntegrationTests ]
    commands:
      - ./MqttSnClientNetworkInterfaceMessageDefragmentationTests --gtest_filter=DefragmentationTests/MqttSnClientNetworkInterfaceMessageDefragmentationTests.*/*:DefragmentationTests/MqttSnClientNetworkInterfaceMessageDefragmentationTests/*.* --gtest_color=no

  - name: SendMultipleClientMultipleMessageVariableLength
    image: ubuntu
    depends_on: [ MqttSnClientNetworkInterfaceMessageDefragmentationTests ]
    commands:
      - ./SendMultipleClientMultipleMessageVariableLength --gtest_filter=MqttSnClientNetworkInterfaceTests.SendMultipleClientMultipleMessageVariableLength:MqttSnClientNetworkInterfaceTests/*.SendMultipleClientMultipleMessageVariableLength:*/MqttSnClientNetworkInterfaceTests.SendMultipleClientMultipleMessageVariableLength/*:*/MqttSnClientNetworkInterfaceTests/*.SendMultipleClientMultipleMessageVariableLength --gtest_color=yes

  - name: ReceiveMultipleClientMultipleMessageVariableLength
    image: ubuntu
    depends_on: [ MqttSnClientNetworkInterfaceMessageDefragmentationTests ]
    commands:
      - ./ReceiveMultipleClientMultipleMessageVariableLength --gtest_filter=MqttSnClientNetworkInterfaceTests.ReceiveMultipleClientMultipleMessageVariableLength:MqttSnClientNetworkInterfaceTests/*.ReceiveMultipleClientMultipleMessageVariableLength:*/MqttSnClientNetworkInterfaceTests.ReceiveMultipleClientMultipleMessageVariableLength/*:*/MqttSnClientNetworkInterfaceTests/*.ReceiveMultipleClientMultipleMessageVariableLength --gtest_color=yes

  - name: SendToClientsReceiveOnForwarderTests
    image: ubuntu
    depends_on: [ MqttSnClientNetworkInterfaceMessageDefragmentationTests ]
    commands:
      - ./SendToClientsReceiveOnForwarderTests --gtest_filter=MqttSnClientNetworkInterfaceTests.SendToClientsReceiveOnForwarderTests:MqttSnClientNetworkInterfaceTests/*.SendToClientsReceiveOnForwarderTests:*/MqttSnClientNetworkInterfaceTests.SendToClientsReceiveOnForwarderTests/*:*/MqttSnClientNetworkInterfaceTests/*.SendToClientsReceiveOnForwarderTests --gtest_color=no

  - name: ReceiveOnForwarderSendToClientTests
    image: ubuntu
    depends_on: [ MqttSnClientNetworkInterfaceMessageDefragmentationTests ]
    commands:
      - ./ReceiveOnForwarderSendToClientTests --gtest_filter=MqttSnClientNetworkInterfaceTests.ReceiveOnForwarderSendToClientTests:MqttSnClientNetworkInterfaceTests/*.ReceiveOnForwarderSendToClientTests:*/MqttSnClientNetworkInterfaceTests.ReceiveOnForwarderSendToClientTests/*:*/MqttSnClientNetworkInterfaceTests/*.ReceiveOnForwarderSendToClientTests --gtest_color=no


  - name: GatewayDefragmentationTests
    image: ubuntu
    depends_on: [ MqttSnClientNetworkInterfaceUnitTests, MqttSnGatewayNetworkInterfaceUnitTests, MqttSnFixedSizeRingBufferUnitTests, MqttSnForwarderIntegrationTests ]
    commands:
      - ./GatewayDefragmentationTests --gtest_filter=GatewayDefragmentationTests/MqttSnGatewayNetworkInterfaceMessageDefragmentationTests.*/*:GatewayDefragmentationTests/MqttSnGatewayNetworkInterfaceMessageDefragmentationTests/*.* --gtest_color=no

  - name: SendToGateway
    image: ubuntu
    depends_on: [ GatewayDefragmentationTests ]
    commands:
      - ./SendToGateway --gtest_filter=MqttSnGatewayNetworkInterfaceSendReceiveTests.SendToGateway:MqttSnGatewayNetworkInterfaceSendReceiveTests/*.SendToGateway:*/MqttSnGatewayNetworkInterfaceSendReceiveTests.SendToGateway/*:*/MqttSnGatewayNetworkInterfaceSendReceiveTests/*.SendToGateway --gtest_color=no

  - name: ReceiveFromGateway
    image: ubuntu
    depends_on: [ GatewayDefragmentationTests ]
    commands:
      - ./ReceiveFromGateway --gtest_filter=MqttSnGatewayNetworkInterfaceSendReceiveTests.ReceiveFromGateway:MqttSnGatewayNetworkInterfaceSendReceiveTests/*.ReceiveFromGateway:*/MqttSnGatewayNetworkInterfaceSendReceiveTests.ReceiveFromGateway/*:*/MqttSnGatewayNetworkInterfaceSendReceiveTests/*.ReceiveFromGateway --gtest_color=no

  - name: SendToGatewayReceiveOnForwarder
    image: ubuntu
    depends_on: [ GatewayDefragmentationTests ]
    commands:
      - ./SendToGatewayReceiveOnForwarder --gtest_filter=MqttSnGatewayNetworkInterfaceSendReceiveTests.SendToGatewayReceiveOnForwarder:MqttSnGatewayNetworkInterfaceSendReceiveTests/*.SendToGatewayReceiveOnForwarder:*/MqttSnGatewayNetworkInterfaceSendReceiveTests.SendToGatewayReceiveOnForwarder/*:*/MqttSnGatewayNetworkInterfaceSendReceiveTests/*.SendToGatewayReceiveOnForwarder --gtest_color=no

  - name: ReceiveFromGatewaySendToGateway
    image: ubuntu
    depends_on: [ GatewayDefragmentationTests ]
    commands:
      - ./ReceiveFromGatewaySendToGateway --gtest_filter=MqttSnGatewayNetworkInterfaceSendReceiveTests.ReceiveFromGatewaySendToGateway:MqttSnGatewayNetworkInterfaceSendReceiveTests/*.ReceiveFromGatewaySendToGateway:*/MqttSnGatewayNetworkInterfaceSendReceiveTests.ReceiveFromGatewaySendToGateway/*:*/MqttSnGatewayNetworkInterfaceSendReceiveTests/*.ReceiveFromGatewaySendToGateway --gtest_color=no

volumes:
  - name: reports
    host:
      path: /var/local/drone/reports
