---
kind: pipeline
name: prepare_reports

steps:
- name: prepare
  image: ubuntu
  volumes:
    - name: reports
      path: /var/local/drone/reports
  commands:
    - mkdir --parents /var/local/drone/reports/${DRONE_REPO}/${DRONE_BUILD_NUMBER}


volumes:
  - name: reports
    host:
      path: /var/local/drone/reports

