kind: pipeline
name: default

steps:
  - name: prepare
    commands:
    - docker build --tag cmakegcc  --file Dockerfile .

  - name: test
    image: cmakegcc
    commands:
    - cmake -DCMAKE_BUILD_TYPE=Debug -G "CodeBlocks - Unix Makefiles"
    - make MqttSnForwarder_LinuxTcpClientNetwork_Tests
    - ./MqttSnForwarder_LinuxTcpClientNetwork_Tests
