kind: pipeline
name: default

steps:
  - name: prepare
    image: ubuntu
    depends_on: [ clone ]
    volumes:
      - name: reports
        path: /var/local/drone/reports
    commands:
      - mkdir --parents /var/local/drone/reports/${DRONE_REPO}/${DRONE_BUILD_NUMBER}
      - echo "DRONE_BRANCH ${DRONE_BRANCH}\n
        DRONE_BUILD_CREATED ${DRONE_BUILD_CREATED}\n
        DRONE_BUILD_EVENT ${DRONE_BUILD_EVENT}\n
        DRONE_BUILD_NUMBER ${DRONE_BUILD_NUMBER}\n
        DRONE_BUILD_STARTED ${DRONE_BUILD_STARTED}\n
        DRONE_COMMIT_AFTER ${DRONE_COMMIT_AFTER}\n
        DRONE_COMMIT_AUTHOR ${DRONE_COMMIT_AUTHOR}\n
        DRONE_COMMIT_AUTHOR_AVATAR ${DRONE_COMMIT_AUTHOR_AVATAR}\n
        DRONE_COMMIT_AUTHOR_EMAIL ${DRONE_COMMIT_AUTHOR_EMAIL}\n
        DRONE_COMMIT_AUTHOR_NAME ${DRONE_COMMIT_AUTHOR_NAME}\n
        DRONE_COMMIT_BEFORE ${DRONE_COMMIT_BEFORE}\n
        DRONE_COMMIT_BRANCH ${DRONE_COMMIT_BRANCH}\n
        DRONE_COMMIT_LINK ${DRONE_COMMIT_LINK}\n
        DRONE_COMMIT ${DRONE_COMMIT}\n
        DRONE_COMMIT_MESSAGE ${DRONE_COMMIT_MESSAGE}\n
        DRONE_COMMIT_REF ${DRONE_COMMIT_REF}\n
        DRONE_COMMIT_SHA ${DRONE_COMMIT_SHA}\n
        DRONE_GIT_HTTP_URL ${DRONE_GIT_HTTP_URL}\n
        DRONE_GIT_SSH_URL ${DRONE_GIT_SSH_URL}\n
        DRONE_MACHINE ${DRONE_MACHINE}\n
        DRONE_PULL_REQUEST ${DRONE_PULL_REQUEST}\n
        DRONE_REPO ${DRONE_REPO}\n
        DRONE_REPO_BRANCH ${DRONE_REPO_BRANCH}\n
        DRONE_REMOTE_URL ${DRONE_REMOTE_URL}\n
        DRONE_REPO_LINK ${DRONE_REPO_LINK}\n
        DRONE_REPO_NAME ${DRONE_REPO_NAME}\n
        DRONE_REPO_NAMESPACE ${DRONE_REPO_NAMESPACE}\n
        DRONE_REPO_PRIVATE ${DRONE_REPO_PRIVATE}\n
        DRONE_REPO_SCM ${DRONE_REPO_SCM}\n
        DRONE_REPO_VISIBILITY ${DRONE_REPO_VISIBILITY}\n
        DRONE_RUNNER_HOST ${DRONE_RUNNER_HOST}\n
        DRONE_RUNNER_HOSTNAME ${DRONE_RUNNER_HOSTNAME}\n
        DRONE_RUNNER_PLATFORM ${DRONE_RUNNER_PLATFORM}\n
        DRONE_SOURCE_BRANCH ${DRONE_SOURCE_BRANCH}\n
        DRONE_SYSTEM_HOST ${DRONE_SYSTEM_HOST}\n
        DRONE_SYSTEM_HOSTNAME ${DRONE_SYSTEM_HOSTNAME}\n
        DRONE_RUNNER_LABEL ${DRONE_RUNNER_LABEL}\n
        DRONE_SYSTEM_VERSION ${DRONE_SYSTEM_VERSION}\n
        DRONE_TAG ${DRONE_TAG}\n
        DRONE_TARGET_BRANCH ${DRONE_TARGET_BRANCH}\n" > /var/local/drone/reports/${DRONE_REPO}/${DRONE_BUILD_NUMBER}/config

  - name: build
    image: ubuntu
    commands:
      - touch apt_report
      - touch cmake_report

  - name: gather_build_report_success
    image: ubuntu
    volumes:
      - name: reports
        path: /var/local/drone/reports
    commands:
      - ls -l
      - cp apt_report /var/local/drone/reports/${DRONE_REPO}/${DRONE_BUILD_NUMBER}/apt_report
      - cp cmake_report /var/local/drone/reports/${DRONE_REPO}/${DRONE_BUILD_NUMBER}/cmake_report
      - cp make_report /var/local/drone/reports/${DRONE_REPO}/${DRONE_BUILD_NUMBER}/make_report
    depeneds_on: [ build ]

  - name: gather_build_report_failure
    image: ubuntu
    volumes:
      - name: reports
        path: /var/local/drone/reports
    commands:
      - ls -l
      - cp apt_report /var/local/drone/reports/${DRONE_REPO}/${DRONE_BUILD_NUMBER}/apt_report
      - cp cmake_report /var/local/drone/reports/${DRONE_REPO}/${DRONE_BUILD_NUMBER}/cmake_report
      - cp make_report /var/local/drone/reports/${DRONE_REPO}/${DRONE_BUILD_NUMBER}/make_report
    when:
      status: [ failure ]
    depeneds_on: [ build ]

  - name: MqttSnClientNetworkInterfaceUnitTests
    image: ubuntu
    depeneds_on: [ build ]
    commands:
      - ./MqttSnClientNetworkInterfaceUnitTests
        --gtest_output=xml:MqttSnClientNetworkInterfaceUnitTests.xml
        --gtest_filter=* --gtest_color=yes

  - name: MqttSnGatewayNetworkInterfaceUnitTests
    image: ubuntu
    depeneds_on: [ build ]
    commands:
      - ./MqttSnGatewayNetworkInterfaceUnitTests
        --gtest_output=xml:MqttSnGatewayNetworkInterfaceUnitTests.xml
        --gtest_filter=* --gtest_color=yes

  - name: MqttSnFixedSizeRingBufferUnitTests
    image: ubuntu
    depeneds_on: [ build ]
    commands:
      - ./MqttSnFixedSizeRingBufferUnitTests
        --gtest_output=xml:MqttSnFixedSizeRingBufferUnitTests.xml
        --gtest_filter=* --gtest_color=yes

  - name: MqttSnForwarderIntegrationTests
    image: ubuntu
    depeneds_on: [ build ]
    commands:
      - ./MqttSnForwarderIntegrationTests
        --gtest_output=xml:MqttSnForwarderIntegrationTests.xml
        --gtest_filter=* --gtest_color=yes

  - name: gather_test_report
    image: ubuntu
    volumes:
      - name: reports
        path: /var/local/drone/reports
    commands:
      - ls -l
      - if [ -e MqttSnClientNetworkInterfaceUnitTests.xml ]; then; cp MqttSnClientNetworkInterfaceUnitTests.xml /var/local/drone/reports/${DRONE_REPO}/${DRONE_BUILD_NUMBER}/MqttSnClientNetworkInterfaceUnitTests.xml; fi
      - cp MqttSnGatewayNetworkInterfaceUnitTests.xml /var/local/drone/reports/${DRONE_REPO}/${DRONE_BUILD_NUMBER}/MqttSnGatewayNetworkInterfaceUnitTests.xml
      - cp MqttSnFixedSizeRingBufferUnitTests.xml /var/local/drone/reports/${DRONE_REPO}/${DRONE_BUILD_NUMBER}/MqttSnFixedSizeRingBufferUnitTests.xml
      - cp MqttSnForwarderIntegrationTests.xml /var/local/drone/reports/${DRONE_REPO}/${DRONE_BUILD_NUMBER}/MqttSnForwarderIntegrationTests.xml
    when:
      status: [ failure ]
    depeneds_on: [ MqttSnClientNetworkInterfaceUnitTests, MqttSnGatewayNetworkInterfaceUnitTests, MqttSnFixedSizeRingBufferUnitTests, MqttSnForwarderIntegrationTests ]


volumes:
  - name: reports
    host:
      path: /var/local/drone/reports
