//
// Created by SomeDude on 25.09.2019.
//

#ifndef CMQTTSNFORWARDER_MQTTSNPARSERARDUINO_HPP
#define CMQTTSNFORWARDER_MQTTSNPARSERARDUINO_HPP

#include <parser/MqttSnAdvertiseMessage.c>
#include <parser/MqttSnAdvertiseMessage.h>
#include <parser/MqttSnConnackMessage.c>
#include <parser/MqttSnConnackMessage.h>
#include <parser/MqttSnConnectMessage.c>
#include <parser/MqttSnConnectMessage.h>
#include <parser/MqttSnDisconnectMessage.c>
#include <parser/MqttSnDisconnectMessage.h>
#include <parser/MqttSnForwarderEncapsulationMessage.c>
#include <parser/MqttSnForwarderEncapsulationMessage.h>
#include <parser/MqttSnGwInfoMessage.c>
#include <parser/MqttSnGwInfoMessage.h>
#include <parser/MqttSnMessageParser.c>
#include <parser/MqttSnMessageParser.h>
#include <parser/MqttSnPingReqMessage.c>
#include <parser/MqttSnPingReqMessage.h>
#include <parser/MqttSnPingRespMessage.c>
#include <parser/MqttSnPingRespMessage.h>
#include <parser/MqttSnPubackMessage.c>
#include <parser/MqttSnPubackMessage.h>
#include <parser/MqttSnPublishMessage.c>
#include <parser/MqttSnPublishMessage.h>
#include <parser/MqttSnPubrecPubrelPubcompMessage.c>
#include <parser/MqttSnPubrecPubrelPubcompMessage.h>
#include <parser/MqttSnRegAckMessage.c>
#include <parser/MqttSnRegAckMessage.h>
#include <parser/MqttSnRegisterMessage.c>
#include <parser/MqttSnRegisterMessage.h>
#include <parser/MqttSnSearchGwMessage.c>
#include <parser/MqttSnSearchGwMessage.h>
#include <parser/MqttSnSubackMessage.c>
#include <parser/MqttSnSubackMessage.h>
#include <parser/MqttSnSubscribeMessage.c>
#include <parser/MqttSnSubscribeMessage.h>
#include <parser/MqttSnUnsubackMessage.c>
#include <parser/MqttSnUnsubackMessage.h>
#include <parser/MqttSnUnsubscribeMessage.c>
#include <parser/MqttSnUnsubscribeMessage.h>
#include <parser/MqttSnWillMsgMessage.c>
#include "parser/MqttSnWillMsgMessageLogging.h"
#include <parser/MqttSnWillMsgReqMessage.c>
#include <parser/MqttSnWillMsgReqMessage.h>
#include <parser/MqttSnWillMsgRespMessage.c>
#include <parser/MqttSnWillMsgRespMessage.h>
#include <parser/MqttSnWillMsgUpdMessage.c>
#include <parser/MqttSnWillMsgUpdMessage.h>
#include <parser/MqttSnWillTopicMessage.c>
#include <parser/MqttSnWillTopicMessage.h>
#include <parser/MqttSnWillTopicReq.c>
#include <parser/MqttSnWillTopicReq.h>
#include <parser/MqttSnWillTopicRespMessage.c>
#include <parser/MqttSnWillTopicRespMessage.h>
#include <parser/MqttSnWillTopicUpdMessage.c>
#include <parser/MqttSnWillTopicUpdMessage.h>

#ifdef WITH_LOGGING
#include <parser/logging/MqttSnAdvertiseMessageLogging.c>
#include <parser/logging/MqttSnAdvertiseMessageLogging.h>
#include <parser/logging/MqttSnConnectMessageLogging.c>
#include <parser/logging/MqttSnConnectMessageLogging.h>
#include <parser/logging/MqttSnDisconnectMessageLogging.c>
#include <parser/logging/MqttSnDisconnectMessageLogging.h>
#include <parser/logging/MqttSnForwarderLoggingMessages.c>
#include <parser/logging/MqttSnForwarderLoggingMessages.h>
#include <parser/logging/MqttSnGwInfoMessageLogging.c>
#include <parser/logging/MqttSnGwInfoMessageLogging.h>
#include <parser/logging/MqttSnMessageParserLogging.c>
#include <parser/logging/MqttSnMessageParserLogging.h>
#include <parser/logging/MqttSnPingReqMessageLogging.c>
#include <parser/logging/MqttSnPingReqMessageLogging.h>
#include <parser/logging/MqttSnPubackMessageLogging.c>
#include <parser/logging/MqttSnPubackMessageLogging.h>
#include <parser/logging/MqttSnPubCompMessageLogging.c>
#include <parser/logging/MqttSnPubackMessageLogging.h>
#include <parser/logging/MqttSnPublishMessageLogging.c>
#include <parser/logging/MqttSnPublishMessageLogging.h>
#include <parser/logging/MqttSnPubrecMessageLogging.c>
#include <parser/logging/MqttSnPubrecMessageLogging.h>
#include <parser/logging/MqttSnPubrelMessageLogging.c>
#include <parser/logging/MqttSnPubrelMessageLogging.h>
#include "parser/logging/MqttSnRegAckMessageLogging.c"
#include "parser/logging/MqttSnRegAckMessageLogging.h"
#include <parser/logging/MqttSnRegisterMessageLogging.c>
#include <parser/logging/MqttSnRegisterMessageLogging.h>
#include <parser/logging/MqttSnSearchGwMessageLogging.c>
#include <parser/logging/MqttSnSearchGwMessageLogging.h>
#include <parser/logging/MqttSnSubscribeMessageLogging.c>
#include <parser/logging/MqttSnSubscribeMessageLogging.h>
#include <parser/logging/MqttSnUnsubscribeMessageLogging.c>
#include <parser/logging/MqttSnUnsubscribeMessageLogging.h>
#include "parser/logging/MqttSnWillMsgMessageLogging.c"
#include <parser/logging/MqttSnWillMsgMessageLogging.h>
#include <parser/logging/MqttSnWillTopicMessageLogging.c>
#include <parser/logging/MqttSnWillTopicMessageLogging.h>
//#include <parser/logging/MqttSnConnackMessageLogging.c>
//#include <parser/logging/MqttSnConnackMessageLogging.h>
#endif
#endif  //CMQTTSNFORWARDER_MQTTSNPARSERARDUINO_HPP
