//
// Created by SomeDude on 14.07.2019.
//

#ifndef CMQTTSNFORWARDER_GATEWAY_MQTTSNGATEWAYSTATUS_H_
#define CMQTTSNFORWARDER_GATEWAY_MQTTSNGATEWAYSTATUS_H_
#ifdef __cplusplus
extern "C" {
#endif

typedef enum MQTT_SN_GATEWAY_STATUS_ {
  MQTT_SN_GATEWAY_STATUS_STAND_BY = 0,
  MQTT_SN_GATEWAY_STATUS_MQTT_DISCONNECTED,
  MQTT_SN_GATEWAY_STATUS_MQTT_SN_DISCONNECTED,
  MQTT_SN_GATEWAY_STATUS_ACTIVE
} MQTT_SN_GATEWAY_STATUS;

#ifdef __cplusplus
}
#endif
#endif //CMQTTSNFORWARDER_GATEWAY_MQTTSNGATEWAYSTATUS_H_
