//
// Created by SomeDude on 24.07.2019.
//

#ifndef CMQTTSNFORWARDER_TEST_MQTTSNFORWARDER_MQTTSNFORWARDERTESTCONTAINERINTERFACE_H_
#define CMQTTSNFORWARDER_TEST_MQTTSNFORWARDER_MQTTSNFORWARDERTESTCONTAINERINTERFACE_H_

class MqttSnForwarderTestContainerInterface {

};

#endif //CMQTTSNFORWARDER_TEST_MQTTSNFORWARDER_MQTTSNFORWARDERTESTCONTAINERINTERFACE_H_
