//
// Created by SomeDude on 17.09.2019.
//

#ifndef CMQTTSNFORWARDER_MQTTSNFORWARDERTESTTYPE_H
#define CMQTTSNFORWARDER_MQTTSNFORWARDERTESTTYPE_H

enum class MqttSnForwarderTestType {
  ARSMB
};

#endif  // CMQTTSNFORWARDER_MQTTSNFORWARDERTESTTYPE_H
