//
// Created by SomeDude on 31.07.2019.
//

#ifndef CMQTTSNFORWARDER_TEST_MQTTSNNETWORKBUILDER_MQTTSNADDRESSGENERATORTYPE_H_
#define CMQTTSNFORWARDER_TEST_MQTTSNNETWORKBUILDER_MQTTSNADDRESSGENERATORTYPE_H_

enum class MqttSnAddressGeneratorType {
  UDP, TCP, // FEATURE BLE, XBEE, BLUETOOTH_MESH, BLUETOOTH_FIVE
};

#endif //CMQTTSNFORWARDER_TEST_MQTTSNNETWORKBUILDER_MQTTSNADDRESSGENERATORTYPE_H_
