//
// Created by SomeDude on 24.07.2019.
//

#ifndef CMQTTSNFORWARDER_TEST_MQTTSNCLIENT_MQTTSNCLIENTPROTOCOLTYPE_H_
#define CMQTTSNFORWARDER_TEST_MQTTSNCLIENT_MQTTSNCLIENTPROTOCOLTYPE_H_

enum class MqttSnClientProtocolType {
  UDP, TCP, ZIGBEE, THREAD, ANT, ANTPLUS, BLUETOOTH, BLUETOOTHFOUR, BLUETOOTHFIVE,BLUETOOTHMESH
};

#endif //CMQTTSNFORWARDER_TEST_MQTTSNCLIENT_MQTTSNCLIENTPROTOCOLTYPE_H_
