//
// Created by SomeDude on 24.07.2019.
//

#ifndef CMQTTSNFORWARDER_TEST_MQTTSNCLIENT_MQTTSNCLIENTACTIONRESULTTYPE_H_
#define CMQTTSNFORWARDER_TEST_MQTTSNCLIENT_MQTTSNCLIENTACTIONRESULTTYPE_H_
#include <iostream>
enum class MqttSnClientActionResultType {
  SUCCESS = 0, ERROR, TIMEOUT, UNKNOWNACTION
};
std::ostream &operator<<(std::ostream &os, const MqttSnClientActionResultType &obj);
#endif //CMQTTSNFORWARDER_TEST_MQTTSNCLIENT_MQTTSNCLIENTACTIONRESULTTYPE_H_
