//
// Created by SomeDude on 24.07.2019.
//

#ifndef CMQTTSNFORWARDER_TEST_MQTTSNCLIENT_MQTTSNCLIENTACTIONTYPE_H_
#define CMQTTSNFORWARDER_TEST_MQTTSNCLIENT_MQTTSNCLIENTACTIONTYPE_H_

enum class MqttSnClientActionType {
  NOCOMMAND,
  INITCLIENT,
  DEINITCLIENT,
  CONNECT,
  ADVERTISECONNECT,
  SEARCHGWCONNECT,
  DIRECTCONNECT,
  DISCONNECT,
  REGISTER,
  SUBSCRIBE,
  UNSUBSCRIBE,
  PUBLISH,
  PUBLISHQOSM1,
  PUBLISHQOSM1CONNECTED,
  PUBLISHQOS0,
  PUBLISHQOS1,
  PUBLISHQOS2,
  SLEEP,
  WAKEUP,
  // TODO WILLTOPICUPD,
  // TODO WILLMSGUPD,
  UNKNOWNACTION,
};

#endif //CMQTTSNFORWARDER_TEST_MQTTSNCLIENT_MQTTSNCLIENTACTIONTYPE_H_
