//
// Created by SomeDude on 24.07.2019.
//

#ifndef CMQTTSNFORWARDER_TEST_MQTTSNCLIENT_MQTTSNCLIENTACTIONRESULTTYPE_H_
#define CMQTTSNFORWARDER_TEST_MQTTSNCLIENT_MQTTSNCLIENTACTIONRESULTTYPE_H_

enum class MqttSnClientActionResultType {
  SUCCESS = 0, ERROR, CONNECTIONLOST, TIMEOUT, UNKNOWNACTION
};

#endif //CMQTTSNFORWARDER_TEST_MQTTSNCLIENT_MQTTSNCLIENTACTIONRESULTTYPE_H_
