//
// Created by SomeDude on 24.07.2019.
//

#ifndef CMQTTSNFORWARDER_TEST_MQTTSNCLIENT_MQTTSNCLIENTACTIONTYPE_H_
#define CMQTTSNFORWARDER_TEST_MQTTSNCLIENT_MQTTSNCLIENTACTIONTYPE_H_

enum class MqttSnClientActionType {
  RECEIVADVERTISE,
  SEARCHGW,
  CONNECT,
  DISCONNECT,
  REGISTER,
  SUBSCRIBE,
  UNSUBSCRIBE,
  PUBLISH,
  SLEEP,
  WAKEUP,
  WILLTOPICUPD,
  WILLMSGUPD
};

#endif //CMQTTSNFORWARDER_TEST_MQTTSNCLIENT_MQTTSNCLIENTACTIONTYPE_H_
