//
// Created by SomeDude on 09.09.2019.
//

#ifndef CMQTTSNFORWARDER_MQTTSNCLIENTPUBLISHTOPICIDTYPE_H
#define CMQTTSNFORWARDER_MQTTSNCLIENTPUBLISHTOPICIDTYPE_H

enum class MqttSnClientPublishTopicIdType { TOPIC_ID, PREDEFINED, SHORT_NAME };

#endif  // CMQTTSNFORWARDER_MQTTSNCLIENTPUBLISHTOPICIDTYPE_H
