//
// Created by SomeDude on 30.07.2019.
//

#ifndef CMQTTSNFORWARDER_TEST_MQTTSNCLIENT_MQTTSNCLIENTPROTOCOLTESTTYPE_H_
#define CMQTTSNFORWARDER_TEST_MQTTSNCLIENT_MQTTSNCLIENTPROTOCOLTESTTYPE_H_

enum class MqttSnClientProtocolTestType {
  UDP, TCP, ZIGBEE, THREAD, ANT, ANTPLUS, BLUETOOTH, BLUETOOTHFOUR, BLUETOOTHFIVE,BLUETOOTHMESH
};

#endif //CMQTTSNFORWARDER_TEST_MQTTSNCLIENT_MQTTSNCLIENTPROTOCOLTESTTYPE_H_
