//
// Created by SomeDude on 30.07.2019.
//

#ifndef CMQTTSNFORWARDER_TEST_MQTTSNCLIENT_MQTTSNCLIENTFINDGATEWAYTYPE_H_
#define CMQTTSNFORWARDER_TEST_MQTTSNCLIENT_MQTTSNCLIENTFINDGATEWAYTYPE_H_

enum class MqttSnClientFindGatewayType {
  ANY, ADVERTISE, SEARCH, CONNECT
};

#endif //CMQTTSNFORWARDER_TEST_MQTTSNCLIENT_MQTTSNCLIENTFINDGATEWAYTYPE_H_
