//
// Created by SomeDude on 09.07.2019.
//

#ifndef CMQTTSNFORWARDER_TEST_MQTTSNTESTLOGGER_MQTTSNTESTLOGGER_H_
#define CMQTTSNFORWARDER_TEST_MQTTSNTESTLOGGER_MQTTSNTESTLOGGER_H_

#endif //CMQTTSNFORWARDER_TEST_MQTTSNTESTLOGGER_MQTTSNTESTLOGGER_H_
