//
// Created by SomeDude on 18.06.2019.
//

#ifndef CMQTTSNFORWARDER_CONFIG_GATEWAY_BROKER_BROKER_CONFIG_H_
#define CMQTTSNFORWARDER_CONFIG_GATEWAY_BROKER_BROKER_CONFIG_H_
// TODO
#endif //CMQTTSNFORWARDER_CONFIG_GATEWAY_BROKER_BROKER_CONFIG_H_
