//
// Created by SomeDude on 22.07.2019.
//

#ifndef CMQTTSNFORWARDER_TEST_MQTTCLIENT_MQTTCLIENTCONNECTACTIONRESULT_H_
#define CMQTTSNFORWARDER_TEST_MQTTCLIENT_MQTTCLIENTCONNECTACTIONRESULT_H_

class MqttClientConnectActionResult {

};

#endif //CMQTTSNFORWARDER_TEST_MQTTCLIENT_MQTTCLIENTCONNECTACTIONRESULT_H_
