//
// Created by SomeDude on 30.07.2019.
//

#ifndef CMQTTSNFORWARDER_TEST_MQTTCLIENT_MQTTCLIENTPROTOCOLTESTTYPE_H_
#define CMQTTSNFORWARDER_TEST_MQTTCLIENT_MQTTCLIENTPROTOCOLTESTTYPE_H_

enum class MqttClientProtocolTestType {
  TCP // TODO , WEBSOCKET
};

#endif //CMQTTSNFORWARDER_TEST_MQTTCLIENT_MQTTCLIENTPROTOCOLTESTTYPE_H_
