//
// Created by SomeDude on 22.07.2019.
//

#ifndef CMQTTSNFORWARDER_TEST_MQTTCLIENT_MQTTCLIENTACTIONTYPE_H_
#define CMQTTSNFORWARDER_TEST_MQTTCLIENT_MQTTCLIENTACTIONTYPE_H_
#include <iostream>
enum class MqttClientActionType {
  CONNECT,
  CONNECT_WITH_WILL,
  DISCONNECT,
  SUBSCRIBE,
  UNSUBSCRIBE,
  PUBLISH,
  PUBLISH_QOS0,
  PUBLISH_QOS1,
  PUBLISH_QOS2,
  PUBLISH_RECEIVE_PUBLISH,
  PUBLISH_RECEIVE_PUBLISH_QOS0,
  PUBLISH_RECEIVE_PUBLISH_QOS1,
  PUBLISH_RECEIVE_PUBLISH_QOS2,
  DELAY,
  UNKNOWNACTION
};
std::ostream &operator<<(std::ostream &os, const MqttClientActionType &obj);
#endif  // CMQTTSNFORWARDER_TEST_MQTTCLIENT_MQTTCLIENTACTIONTYPE_H_
