//
// Created by SomeDude on 19.04.2019.
//

#ifndef CMQTTSNFORWARDER_PLUGINS_NETWORK_GATEWAY_PLUGIN_HIREDIS_GATEWAY_NETWORK_PLUGIN_H_
#define CMQTTSNFORWARDER_PLUGINS_NETWORK_GATEWAY_PLUGIN_HIREDIS_GATEWAY_NETWORK_PLUGIN_H_

#include <hiredis.h>

#endif //CMQTTSNFORWARDER_PLUGINS_NETWORK_GATEWAY_PLUGIN_HIREDIS_GATEWAY_NETWORK_PLUGIN_H_
