//
// Created by SomeDude on 01.04.2019.
//

#ifndef CMQTTSNFORWARDER_MOCKGATEWAYLINUXUDPNETWORKIMPLEMENTATION_H
#define CMQTTSNFORWARDER_MOCKGATEWAYLINUXUDPNETWORKIMPLEMENTATION_H

class MockGatewayLinuxUdpNetworkImplementation {

};

#endif //CMQTTSNFORWARDER_MOCKGATEWAYLINUXUDPNETWORKIMPLEMENTATION_H
