//
// Created by SomeDude on 30.07.2019.
//

#ifndef CMQTTSNFORWARDER_TEST_MQTTSNNETWORKBUILDER_MQTTSNGATEWAYPROTOCOLTESTTYPE_H_
#define CMQTTSNFORWARDER_TEST_MQTTSNNETWORKBUILDER_MQTTSNGATEWAYPROTOCOLTESTTYPE_H_

enum class MqttSnGatewayProtocolTestType {
  UDP, TCP, ZIGBEE, THREAD, ANT, ANTPLUS, BLUETOOTH, BLUETOOTHFOUR, BLUETOOTHFIVE,BLUETOOTHMESH
};

#endif //CMQTTSNFORWARDER_TEST_MQTTSNNETWORKBUILDER_MQTTSNGATEWAYPROTOCOLTESTTYPE_H_
