//
// Created by SomeDude on 19.07.2019.
//

#ifndef CMQTTSNFORWARDER_TEST_MQTTSNGATEWAY_MQTTSNGATEWAYTESTTYPE_H_
#define CMQTTSNFORWARDER_TEST_MQTTSNGATEWAY_MQTTSNGATEWAYTESTTYPE_H_


enum class MqttSnGatewayTestType {
  ARSMB = 0, PAHO = 1
};

const char *getTextFromEnum(MqttSnGatewayTestType enumVal);

#endif //CMQTTSNFORWARDER_TEST_MQTTSNGATEWAY_MQTTSNGATEWAYTESTTYPE_H_
