//
// Created by bele on 26.02.19.
//

#ifndef CMQTTSNFORWARDER_MQTTSNGATEWAYNETWORKMESSAGEDATAGENERATOR_H
#define CMQTTSNFORWARDER_MQTTSNGATEWAYNETWORKMESSAGEDATAGENERATOR_H

#include <cstdint>

uint8_t *defaultMessageDataGenerator(uint8_t *arr, uint16_t len);

#endif //CMQTTSNFORWARDER_MQTTSNGATEWAYNETWORKMESSAGEDATAGENERATOR_H
