//
// Created by SomeDude on 07.03.2019.
//

#ifndef CMQTTSNFORWARDER_PLACEHOLDERNETWORKCONTEXT_H
#define CMQTTSNFORWARDER_PLACEHOLDERNETWORKCONTEXT_H

class PlaceholderContext {
  
};

#endif //CMQTTSNFORWARDER_PLACEHOLDERNETWORKCONTEXT_H
